---
- name: restart hbase-master
  service: name=hbase-master state=restarted enabled=yes
  when: test is undefined or not test

- name: restart hbase-regionserver
  service: name=hbase-regionserver state=restarted enabled=yes
  when: test is undefined or not test

