---
- name: iptables stop chkconfig iptables off
  service: name=iptables state=stopped enabled=no
  ignore_errors: yes

- name: chkconfig ip6tables off
  service: name=ip6tables state=stopped enabled=no
  ignore_errors: yes

- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: check SELinux is enforcing
  command: getenforce
  register: selinux_result

- name: disable SELinux with command
  command: setenforce 0
  when: selinux_result == "Enforcing"

- name: disable SELinux config
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

- name: install dependency modules
  yum: name={{item}} state=present
  with_items:
    - gcc
    - kernel-devel
    - perl
    - tcl
    - make
    - wget
    - ruby
    - git
    - vim
