---
#- name: iptables stop and chkconfig iptables off
#  service: name=iptables state=stopped enabled=no

#- name: chkconfig ip6tables off
#  service: name=ip6tables state=stopped enabled=no

- name: test
  command: echo "test is undefined or not test"
  when: test is undefined or not test

- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: check SELinux is enforcing
  command: getenforce
  register: selinux_result

- name: disable SELinux with command
  command: setenforce 0
  when: selinux_result == "Enforcing"

#- name: disable SELinux config
#  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

#- name: set DNS1
#  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 insertafter=EOF line=DNS1=8.8.8.8
#- name: restart network
#  service: name=network state=restarted

#- name: Defaults requiretty, configure sudoers
#  lineinfile: dest=/etc/sudoers state=present regexp="^Defaults requiretty" line="#Defaults requiretty"

- name: install dependency modules
  yum: name={{item}} state=present
  with_items:
    - sudo
    - gcc
    - kernel-devel
    - perl
    - tcl
    - make
    - wget
    - tar
    - ruby
    - git
    - vim

