---
- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - common
    - oracle_jdk7
  tags:
    - common

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - cdh_common
  tags:
    - hadoop

- hosts: cdh
  remote_user: vagrant
  become: yes
  become_user: hdfs
  roles:
    - hadoop_namenode
  tags:
    - hadoop

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - hadoop_start
  tags: hadoop

- hosts: cdh
  remote_user: vagrant
  become: yes
  become_user: hdfs
  roles:
    - hadoop_hdfs_directory
  tags:
    - hadoop

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - hadoop_start_resourcemanager
  tags:
    - hadoop

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - zookeeper_server
  tags:
    - zookeeper

- hosts: cdh
  remote_user: vagrant
  become: yes
  become_user: hdfs
  roles:
    - hbase_hdfs_directory
  tags:
    - hbase

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - hbase_master
    - hbase_regionserver
    - hbase_config
  tags:
    - hbase

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - mariadb
  tags:
    - mariadb

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - mysql_connector_java
  tags:
    - mysql_connector_java

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - hive
  tags:
    - hive

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - redis
  tags:
    - redis

- hosts: cdh
  remote_user: vagrant
  become: yes
  roles:
    - sbt
  tags:
    - sbt
