---
- name: install zookeeper-server via yum
  yum: name={{ item }} state=present
  with_items:
    - zookeeper
    - zookeeper-server

- name: create /var/lib/zookeeper directory
  file: path=/var/lib/zookeeper owner=zookeeper group=zookeeper state=directory

- name: copy /etc/zookeeper/conf.dist to /etc/zookeeper/conf.mycluster
  command: cp -R -p /etc/zookeeper/conf.dist /etc/zookeeper/conf.mycluster creates=/etc/zookeeper/conf.mycluster

- name: configure ZooKeeper in /etc/zookeeper/conf.mycluster
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf.mycluster/zoo.cfg owner=zookeeper group=zookeeper mode=0644

- name: run update-alternatives to install zookeeper configuration
  command: update-alternatives --install /etc/zookeeper/conf zookeeper-conf /etc/zookeeper/conf.mycluster 50

- name: run update-alternatives to set zookeeper configuration
  command: update-alternatives --set zookeeper-conf /etc/zookeeper/conf.mycluster

- name: initialize ZooKeeper
  command: creates=/var/lib/zookeeper/myid service zookeeper-server init --myid={{ zookeeper_id }}

- name: start zookeeper
  service: name=zookeeper-server state=started
